version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codedeploy
hooks:
  ApplicationStart:
    - location: scripts/ApplicationStart
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop
      timeout: 300
      runas: root