version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/master-server
hooks:
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root