version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/master-server
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 900
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300