name: Branch Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build_only:
    name: Build only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          lfs: true

      - name: Build Docker image
        run: docker build -t webgl-client-service/test-image .