name: PR Pipeline

on:
  pull_request:

jobs:
  synchronise_with_staging_ci_branch:
    name: Synchronise with staging-ci branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Push to staging-ci branch
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: staging-ci
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start primary pipeline on staging-ci branch
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.RYAN_PERSONAL_TOKEN }}
          event-type: start